import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "./StylingComponents/index.css";
import ControlledForm from "./ControlledForm/InteractiveWelcome.jsx";
import MultipleForm from "./MultipleForm.jsx";
import ValidatedForm from "./ValidatedForm.jsx";
import UncontrolledLogin from "./UncotrolledForm/UncontrolledForm.jsx";
import Login from "./StylingComponents/Login.jsx";
import InteractiveWelcome from "./ControlledForm/InteractiveWelcome.jsx";
import FocusableInput from "./Refs/FocusableInput.jsx";
import DomSample from "./DomSample.jsx";
import RenderState from "./RenderState.jsx";
import NotificationApp from "./NotificationApp.jsx";
import Events from "./Events/Events.jsx";
import Hello from "./Hello.jsx";
import HelloLanguage from "./Context.jsx/HelloLanguage.jsx";
import SecondApp from "./ComponentComposition/SecondApp.jsx";
import UsersWithoutCallback from "./UsersWithoutCallback.jsx";
import MemoUseCase from "./MemoUseCase.jsx";
import TodoListApp from "./TodoListApp.jsx";
import GithubUser from "./GithubUser/GithubUser.jsx";
import Counter from "./ReactRouter/Counter.jsx";
import Form from "./CustomHooks/Form.jsx";
import SWR from "./SWR/SWR.jsx";
import NewApp from "./SWR/NewApp.jsx";
import ReactRouter from "./ReactRouter/ReactRouter.jsx";
import RouterApp from "./ReactRouter/RouterApp.jsx";
import Counters from "./UseState/Counters.jsx";
import CounterEffect from "./UseEffect/CounterEffect.jsx";
import MouseClicker from "./HandlingEvents/MouseClicker.jsx";
import ReacApp2 from "./React-App-2/ReactApp2.jsx";
import RenderColors from "./List/RenderColors.jsx";
import TodoList from "./TodoList/TodoList.jsx";
import CounterDisplay from "./StylingComponents/CounterDisplay.jsx";
import GithubUsers from "./GithubUser/GithubUsers.jsx";

createRoot(document.getElementById("root")).render(<GithubUsers />);
